/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itse322.project.Frames.teachers;

import itse322.project.Frames.students.*;
import itse322.project.Controllers.CoursesController;
import itse322.project.Controllers.StudentController;
import itse322.project.Controllers.TeacherController;
import itse322.project.LoggedUser;
import itse322.project.Message;
import itse322.project.Models.Course;
import itse322.project.Models.Student;
import itse322.project.Models.Teacher;
import java.awt.Color;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.awt.Dimension;
import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.apache.log4j.Logger;

/**
 *
 * @author Mahmoud
 */
public class TeacherDetails extends javax.swing.JFrame {
        
    TeacherController teacherController = new TeacherController();
    Teacher teacher = null;
    CoursesController coursesController = new CoursesController();
    Logger log = Logger.getLogger(TeacherDetails.class);

    /**
     * Creates new form StudentDetails
     */
    public TeacherDetails() {
        initComponents();
    }
    
    public TeacherDetails(Teacher teacher) {
        initComponents();
        this.teacher = teacher;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        teacherName.setText(teacher.getFirstName() + " " + teacher.getLastName() + "'s details");
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherDetailsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        teacherName = new javax.swing.JLabel();
        deleteRegestrationBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setTitle("Teacher details");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Hours", "Start Date", "End Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(teacherDetailsTable);
        if (teacherDetailsTable.getColumnModel().getColumnCount() > 0) {
            teacherDetailsTable.getColumnModel().getColumn(0).setResizable(false);
            teacherDetailsTable.getColumnModel().getColumn(1).setResizable(false);
            teacherDetailsTable.getColumnModel().getColumn(2).setResizable(false);
            teacherDetailsTable.getColumnModel().getColumn(3).setResizable(false);
            teacherDetailsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1370, -1));

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));
        jPanel2.setPreferredSize(new java.awt.Dimension(1422, 150));

        teacherName.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        teacherName.setForeground(new java.awt.Color(255, 255, 255));
        teacherName.setText("Teacher Name here :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(teacherName)
                .addContainerGap(984, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(teacherName)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 150));

        deleteRegestrationBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahmoud\\Documents\\NetBeansProjects\\ITSE322 Project\\Icons\\delete.png")); // NOI18N
        deleteRegestrationBtn.setText("Detele Regestration");
        deleteRegestrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRegestrationBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteRegestrationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahmoud\\Documents\\NetBeansProjects\\ITSE322 Project\\Icons\\back.png")); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 132, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteRegestrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRegestrationBtnActionPerformed
        int selectedRow = teacherDetailsTable.getSelectedRow();
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        if(selectedRow != -1) {
            int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to delete this regestration ?","Warning", dialogButton);
            if(dialogResult == JOptionPane.NO_OPTION){
              return;
            }
        }
       
        if(selectedRow != -1) {
            int tid = teacher.getId();
            int cid = Integer.parseInt(String.valueOf(teacherDetailsTable.getValueAt(selectedRow, 0) ) );
            int row = teacherDetailsTable.convertRowIndexToModel(selectedRow);
            teacherController.deleteRegestrationForTeacher(tid, cid);
            log.info(LoggedUser.getUsername() + " Removed Course " + teacherDetailsTable.getValueAt(selectedRow, 1) + " From " + teacher.getFirstName() + " " + teacher.getLastName());
            DefaultTableModel model = (DefaultTableModel)teacherDetailsTable.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_deleteRegestrationBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherDetails().setVisible(true);
            }
        });
    }
    
    private void refreshTable() {
        teacherDetailsTable.setModel(getTableContent());
        teacherDetailsTable.setGridColor(Color.white);
        teacherDetailsTable.setRowHeight(30);
        teacherDetailsTable.setBackground(new java.awt.Color(255, 255, 255));
        teacherDetailsTable.setFont(new java.awt.Font("Dialog", 1, 14));
        teacherDetailsTable.setShowGrid(false);
        JTableHeader header = teacherDetailsTable.getTableHeader();
        header.setBackground(new java.awt.Color(25,118,210));
        header.setForeground(Color.white);
        header.setAlignmentX(LEFT_ALIGNMENT);
        header.setPreferredSize(new Dimension(jScrollPane1.getWidth(), 30));
        
    }
    
    //return model contains all content to put in a table
    private DefaultTableModel getTableContent() {
        String[] columnNames = {"Course Id", "Course Name","Hours", "Start Date", "End Date"};

        DefaultTableModel dtm = new DefaultTableModel(columnNames, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };

        dtm.setColumnCount(5);
        
        
        Teacher teacherDetails = teacherController.getTeacherByIdWithCourses(teacher.getId());
        
        for(Course c : teacherDetails.getCourses()) {
            dtm.addRow(new Object[] {
                c.getId(),
                c.getCourseName(),
                c.getHours(),
                c.getStartDate(),
                c.getEndDate()
            });
        }
        
        return dtm;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteRegestrationBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable teacherDetailsTable;
    private javax.swing.JLabel teacherName;
    // End of variables declaration//GEN-END:variables
}
